apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: Swaroop-s-Porfolio-deployment
spec:
  selector:
    matchLabels:
      app: Swaroop-s-Porfolio
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: Swaroop-s-Porfolio
    spec:
      containers:
        - name: Swaroop-s-Porfolio
          image: sonuswaroopraj/Swaroop-s-Portfolio:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: Swaroop-s-Porfolio-ssvc
spec:
  selector:
    app: Swaroop-s-Porfolio
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
